import { StyleSheet, Platform } from 'react-native';

export const screenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  centered: {
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center',
  },
  filterBarContainer: {
    backgroundColor: '#fff', 
    paddingVertical: 12, 
    borderBottomWidth: 1, 
    borderBottomColor: '#eee',
  },
  filterTabButton: {
    paddingHorizontal: 14, 
    paddingVertical: 8, 
    borderRadius: 20, 
    marginRight: 8, 
    backgroundColor: '#f5f5f5',
  },
  filterTabText: {
    fontWeight: 'bold', 
    fontSize: 11,
  },
  orderCard: {
    marginBottom: 15,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#fff',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  orderCardGradient: {
    padding: 15,
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  headerLeftRef: {
    flex: 1, 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 6,
  },
  orderIdLabel: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333',
  },
  dateText: {
    fontSize: 10, 
    color: '#888', 
    marginBottom: 10,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  customerCard: {
    backgroundColor: '#fafafa',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  customerRow: {
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between',
  },
  customerMainLeft: {
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 10,
  },
  avatarCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#eaeaea',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#666',
  },
  customerNameMain: {
    fontSize: 13,
    fontWeight: '600',
    color: '#444',
  },
  expandedDetails: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 8,
    gap: 4,
  },
  detailText: {
    fontSize: 11,
    color: '#666',
  },
  selfPickupBadge: {
    backgroundColor: '#E3F2FD', 
    padding: 5, 
    borderRadius: 4, 
    marginTop: 5,
    alignSelf: 'flex-start',
  },
  selfPickupText: {
    fontSize: 9, 
    color: '#1976D2', 
    fontWeight: 'bold',
  },
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 14,
    backgroundColor: '#fafafa',
    padding: 10,
    borderRadius: 8,
  },
  stepBlock: {
    alignItems: 'center', 
    flex: 1,
  },
  progressIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  progressText: {
    fontSize: 9,
    fontWeight: '600',
  },
  itemRowImproved: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  itemImageSmall: {
    width: 36,
    height: 36,
    borderRadius: 6,
    backgroundColor: '#eee',
  },
  itemInfo: {
    flex: 1,
    marginLeft: 10,
  },
  itemNameSmall: {
    fontSize: 12,
    fontWeight: '500',
    color: '#333',
  },
  itemCatSmall: {
    fontSize: 10,
    color: '#888',
    marginTop: 2,
  },
  itemPriceSmall: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  totalLabel: {
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
  },
  totalValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#DAA520',
  },
  actionsContainer: {
    flexDirection: 'row',
    gap: 10, 
    marginTop: 15,
  },
  actionButtonGradient: {
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  emptyContainer: {
    marginTop: 100, 
    alignItems: 'center',
  },
  emptyText: {
    color: '#999', 
    marginTop: 10, 
    fontSize: 15,
  },
});