import { StyleSheet, Platform } from 'react-native';

export const screenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
    marginBottom:50
  },
  centered: {
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center',
  },
  filterBarContainer: {
    backgroundColor: '#FAF8F3',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EBE2D3',
  },
  filterTabButton: {
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: '#EFE9DD',
    borderWidth: 1,
    borderColor: '#E2D7C5',
  },
  filterTabButtonActive: {
    backgroundColor: '#3B3021',
    borderColor: '#3B3021',
  },
  filterTabText: {
    fontWeight: '600',
    fontSize: 11,
    color: '#6E614F',
  },
  filterTabTextActive: {
    fontWeight: '700',
    fontSize: 11,
    color: '#FFF8E8',
  },
  dateFilterCard: {
    backgroundColor: '#FFFDF9',
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EFE7D8',
  },
  dateFilterHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  dateFilterHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateFilterIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: 'rgba(218, 165, 32, 0.14)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(218, 165, 32, 0.25)',
  },
  dateFilterTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#3B3021',
    letterSpacing: 0.2,
  },
  dateFilterSubtitle: {
    fontSize: 11,
    color: '#8A7A63',
    fontWeight: '500',
  },
  dateFilterResetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(218, 165, 32, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(218, 165, 32, 0.25)',
  },
  dateFilterResetText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#A07800',
  },
  customDateBanner: {
    marginHorizontal: 15,
    marginTop: 8,
    marginBottom: 2,
    padding: 10,
    backgroundColor: '#FAF5EA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E6D9C3',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  customDateBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  customDateBannerIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#DAA520',
    justifyContent: 'center',
    alignItems: 'center',
  },
  customDateBannerTitle: {
    fontSize: 10,
    fontWeight: '600',
    color: '#8A7A63',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  customDateBannerDate: {
    fontSize: 13,
    fontWeight: '700',
    color: '#2C2214',
    marginTop: 1,
  },
  customDateActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FFF',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0D2BC',
  },
  customDateActionText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#63533E',
  },
  orderCard: {
    marginBottom: 10,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#fff',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  orderCardGradient: {
    padding: 15,
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  headerLeftRef: {
    flex: 1, 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 6,
  },
  orderIdLabel: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333',
  },
  dateText: {
    fontSize: 10, 
    color: '#888', 
    marginBottom: 10,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  customerCard: {
    backgroundColor: '#fafafa',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  customerRow: {
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between',
  },
  customerMainLeft: {
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 10,
  },
  avatarCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#eaeaea',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#666',
  },
  customerNameMain: {
    fontSize: 13,
    fontWeight: '600',
    color: '#444',
  },
  expandedDetails: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 8,
    gap: 4,
  },
  detailText: {
    fontSize: 11,
    color: '#666',
  },
  selfPickupBadge: {
    backgroundColor: '#E3F2FD', 
    padding: 5, 
    borderRadius: 4, 
    marginTop: 5,
    alignSelf: 'flex-start',
  },
  selfPickupText: {
    fontSize: 9, 
    color: '#1976D2', 
    fontWeight: 'bold',
  },
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 14,
    backgroundColor: '#fafafa',
    padding: 10,
    borderRadius: 8,
  },
  stepBlock: {
    alignItems: 'center', 
    flex: 1,
  },
  progressIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  progressText: {
    fontSize: 9,
    fontWeight: '600',
  },
  itemRowImproved: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  itemImageSmall: {
    width: 36,
    height: 36,
    borderRadius: 6,
    backgroundColor: '#eee',
  },
  itemInfo: {
    flex: 1,
    marginLeft: 10,
  },
  itemNameSmall: {
    fontSize: 12,
    fontWeight: '500',
    color: '#333',
  },
  itemCatSmall: {
    fontSize: 10,
    color: '#888',
    marginTop: 2,
  },
  itemPriceSmall: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  totalLabel: {
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
  },
  totalValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#DAA520',
  },
  actionsContainer: {
    flexDirection: 'row',
    gap: 10, 
    marginTop: 15,
  },
  actionButtonGradient: {
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  emptyContainer: {
    marginTop: 100, 
    alignItems: 'center',
  },
  emptyText: {
    color: '#999', 
    marginTop: 10, 
    fontSize: 15,
  },
});